### ISSUE TITLE
Variable not found: bootstrap-taginput

### ISSUE THREAD

**Issue by billh93** [yogiben/meteor-autoform-tags#11]
Can anybody tell me what I put inside this code. I've placed the bootstrap-taginput options but meteor can't seem to find it. I tried it in so many variations and still no luck.

autoform: {
            type: 'tags',
            afFieldInput: {
                /\* What do i put here? */
            }
        }

**Comment by mpowaga** [comment]
See bootstrap-tagsinput options [here](http://timschlechter.github.io/bootstrap-tagsinput/examples/#options). Example:

``` javascript
autoform: {
  type: 'tags',
  afFieldInput: {
    tagClass: 'big',
    itemText: 'label'
    // ...
  }
}
```
