### ISSUE TITLE
Does this work with Typeahead?

### ISSUE THREAD

**Issue by jchan202** [yogiben/meteor-autoform-tags#16]
Excellent work!!  However, when I try it with Typeahead, it doesn't work.  Here's my bootstrap-tagsinput option:

afFieldInput: {typeahead: {source: ['Amsterdam', 'Washington', 'Sydney', 'Beijing', 'Cairo']}}

**Comment by WadeWarren** [comment]
I'm also having a similar problem!

**Comment by jchan202** [comment]
It works with Typeahead!!  Use '{typeaheadjs: ...' and a function as the source.
