### ISSUE TITLE
Implementing with Meteor/Autoform - no luck.

### ISSUE THREAD

**Issue by gkodikara** [yogiben/meteor-autoform-tags#5]
I've tried to implement this based on the example provided but can't seem to get it to work.
I'm getting - 
"unexpected indentation (compiling both/collections/events.coffee) (at handler)"

Could you provide me a basic way of implementing this or tell me what might be wrong with the example code - maybe theres some implied swapout I'm not doing?

Thanks for any help.

**Comment by mpowaga** [comment]
@gkodikara Can you try again? Maybe this issue was fixed by the new version.
