### ISSUE TITLE
Update to autoform 5.X.X compatibility?

### ISSUE THREAD

**Issue by dkmooers** [yogiben/meteor-autoform-tags#6]
I just upgraded all my forms to Autoform 5.1.0 compatibility, and can't find a single tag input type package that works with it. This is the only tags library I've been able to get to work at all, but limits autoform to 4.2.2. Any chance on updating it to 5.1.0+ compatibility?

**Comment by bshamblen** [comment]
+1

**Comment by greenik** [comment]
+1

**Comment by haydnhkim** [comment]
I'm waiting to merge this PR.
https://github.com/yogiben/meteor-autoform-tags/pull/8

**Comment by romans127** [comment]
Not sure why it has taken this long to get a reply , 
in the meantime someone could fork the project and remove the constraint. Then publish as a forked package.

**Comment by haydnhkim** [comment]
[ahmetcetin:autoform-tags](https://github.com/ahmetcetin/meteor-autoform-tags) package works fine.
I replaced with it.

**Comment by romans127** [comment]
@haydnhkim do you have an example on how to render the tags on the front end in a template. For instance if I have tags on a blog post and I want to display them when the post is rendered.

**Comment by haydnhkim** [comment]
In modify? you should write value then able to modify it.

```
{{> afFieldInput name="tags" value=this.tags}}
```

just view?

```
{{#each tags}}
    {{this}}
{{/each}}
```

**Comment by romans127** [comment]
Thank you for the example. What if I am already looping through a collection such as posts. would it be posts.tags ?

**Comment by haydnhkim** [comment]
@rwatts3 Yes! You can access `posts.tags`.
oh! I got it what you're saying.

```
{{#each posts}}
    {{#each this.tags}}
        {{this}} <- tag
    {{/each}}
{{/each}}
```

it is possible looping array in array.

**Comment by romans127** [comment]
Awesome ok one final question I nearly have all the info I need to build my functionality. 

So I have posts that have categories. How would I make it so that I can pass a param in the url of ?categories=people , and return data to the page, or only the posts that have a category of people

**Comment by haydnhkim** [comment]
@rwatts3 well...
inside route

```
var category = this.params.categories;
var posts = Posts.find({categories: category})
```

I think it can be solved that's problems.

**Comment by mpowaga** [comment]
Version 0.1.2 now supports the latest autoform.
